baseURL = "https://paulmairot.github.io/LabVeilleTech"
languageCode = "fr-CH"
title = "Laboratoire de Veille Technologique - Paul"
theme =  "hugo-theme-anubis"

paginate = 6

[menu]

[[menu.main]]
name = "Articles"
identifier = "archive"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 3
