baseURL = "https://example.com"
languageCode = "fr-CH"
title = "LabVeilleTech - Paul"
theme = "anubis"

paginate = 6

[menu]

[[menu.main]]
name = "Posts"
identifier = "archive"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
